image: alexcazacu1/hylo-base-image-cicd:1.0.1
stages:
  - format
  - build
  - test

format-job:
  stage: format
  script:
    - swift-format lint -r --configuration .swift-format.json -p Sources Tests Package.swift

build-job:
  stage: build
  script:
    - swift build -c debug
  artifacts:
    paths: [.build/]

cli-tests-job:
  stage: test
  needs: [build-job]
  script: 
    - swift test --filter CLITests

code-gen-tests-job:
  stage: test
  needs: [build-job]
  script:
    - swift test --filter WebsiteGenTests

frontend-tests-job:
  stage: test
  needs: [build-job]
  script:
    - swift test --filter DocExtractorTests