image: processeus/hylo-base-image:1.0.0
stages:
  - build
  - test

build-job:
  stage: build
  script:
    - swift build -c debug
  artifacts:
    paths: [.build/]

cli-tests-job:
  stage: test
  needs: [build-job]
  script: 
    - swift test --filter CLITests

code-gen-tests-job:
  stage: test
  needs: [build-job]
  script:
    - swift test --filter WebsiteGenTests

frontend-tests-job:
  stage: test
  needs: [build-job]
  script:
    - swift test --filter DocExtractorTests