FROM processeus/hylo-base-image:1.0.0
# This image is managed by Ambrus, let him know if you want to update. If you can't change this address
# to your own image, you can modify the source.Dockerfile, build an image and push it to Docker Hub.
# Make sure to add a tag to the image, otherwise (if :latest is used) the image will be pulled every
# time you run the pipeline.